package com.babyvault.inference

// Generated by UniFFI — replaced by `core/build.sh` after running cargo ndk.
// This stub allows Android Studio to compile before native libs are built.

class NativeInferenceEngine(modelDir: String) {
    fun isReady(): Boolean = false
    fun generateStream(prompt: String, maxTokens: UInt): TokenStream = TokenStream()
}

class TokenStream {
    fun nextToken(): String? = null
}
